spring.application.name=interviewcoach
server.port=8080
ai.face.url=http://localhost:5001
ai.text.url=http://localhost:8000
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
# Increase request timeout to 5 minutes
spring.mvc.async.request-timeout=300000
# (Optional, if using WebFlux)
spring.webflux.request-timeout=300000
# Increase connection timeouts
server.tomcat.connection-timeout=300000
spring.webflux.timeout=120000
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
